"""empty message

Revision ID: 398dfbfcb43f
Revises: a46be8840cdc
Create Date: 2017-03-20 21:55:19.130747

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '398dfbfcb43f'
down_revision = 'a46be8840cdc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('about_me', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('last_seen', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('location', sa.String(length=64), nullable=True))
    op.add_column('users', sa.Column('realname', sa.String(length=64), nullable=True))
    op.add_column('users', sa.Column('register_since', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'register_since')
    op.drop_column('users', 'realname')
    op.drop_column('users', 'location')
    op.drop_column('users', 'last_seen')
    op.drop_column('users', 'about_me')
    # ### end Alembic commands ###
