"""empty message

Revision ID: 611bf81d8ffb
Revises: 7aed65886737
Create Date: 2017-03-21 11:53:29.820971

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '611bf81d8ffb'
down_revision = '7aed65886737'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('favicon_name', sa.String(length=64), nullable=True))
    op.drop_column('users', 'favicon')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('favicon', sa.BLOB(), nullable=True))
    op.drop_column('users', 'favicon_name')
    # ### end Alembic commands ###
