"""empty message

Revision ID: 7aed65886737
Revises: 398dfbfcb43f
Create Date: 2017-03-21 11:15:29.411539

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7aed65886737'
down_revision = '398dfbfcb43f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('favicon', sa.LargeBinary(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'favicon')
    # ### end Alembic commands ###
